print ('CAIXA:')
print ('**************')
print ('**          **')
print ('**          **')
print ('**          **')
print ('**          **')
print ('**************')


print ('OVAL:')
print ("   ***   ")
print (" **   **")
print ("**     **")
print (" **   **")
print ("   ***   ")

print("SETA:")
print("    *    ")
print("   ***   ")
print("  *****  ")
print(" ******* ")
print("*********")
print("    *    ")
    
print("LOSANGO:")
print("    *    ")
print("   * *   ")
print("  *   *  ")
print(" *     * ")
print("  *   *  ")
print("   * *   ")
print("    *    ")